{
 "title": "Podsumowanie wydatków",
 "time": { "from": "now/y", "to": "now/y" },
 "panels": [
  { "title": "Podsumowanie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Zarobki",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  sum(value)/100 AS \"Zarobki\"\r\nFROM bank_records \r\nWHERE \r\n  date_trunc('MONTH', date) >= date_trunc('MONTH', $__timeFrom()::date)\r\n  AND date_trunc('MONTH', date) <= date_trunc('MONTH', $__timeTo()::date)\r\n  AND category = 'WYNAGRODZENIE'"
    }
   ]
  },
  {
   "title": "Średnie miesięczne zarobki",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH months as (\r\n  SELECT  \r\n  generate_series(\r\n    date_trunc('MONTH', $__timeFrom()::date),\r\n    date_trunc('MONTH', $__timeTo()::date),\r\n    interval '1 MONTH'\r\n  )::date as month)\r\n\r\n\r\nSELECT \r\n  sum(value)/100/count(distinct m.month) AS \"Zarobki\"\r\nFROM months m\r\nLEFT JOIN bank_records br ON m.month = date_trunc('MONTH', br.date)::date AND br.category = 'WYNAGRODZENIE'"
    }
   ]
  },
  {
   "title": "Wydatki",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  sum(value)/100 AS \"Zarobki\"\r\nFROM bank_records\r\nWHERE \r\n  value < 0\r\n  AND date_trunc('MONTH', date) >= date_trunc('MONTH', $__timeFrom()::date)\r\n  AND date_trunc('MONTH', date) <= date_trunc('MONTH', $__timeTo()::date)\r\n  AND category != 'INWESTYCJE'"
    }
   ]
  },
  {
   "title": "Średnie miesięczne wydatki",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH months as (\r\n  SELECT  \r\n  generate_series(\r\n    date_trunc('MONTH', $__timeFrom()::date),\r\n    date_trunc('MONTH', $__timeTo()::date),\r\n    interval '1 MONTH'\r\n  )::date as month)\r\n\r\n\r\nSELECT \r\n  sum(value)/100/count(distinct m.month) AS \"Wydatki\"\r\nFROM months m\r\nLEFT JOIN bank_records br ON m.month = date_trunc('MONTH', br.date)::date AND br.category != 'INWESTYCJE'\r\nWHERE br.value < 0"
    }
   ]
  },
  {
   "title": "Top 10 kategorii pod względem kwoty",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT   \r\n  category as \"Kategoria\",\r\n  sum(value/-100.0)\r\nFROM bank_records\r\nWHERE \r\n  value < 0\r\n  AND date_trunc('MONTH', date) >= date_trunc('MONTH', $__timeFrom()::date)\r\n  AND date_trunc('MONTH', date) <= date_trunc('MONTH', $__timeTo()::date)\r\n  AND category != 'INWESTYCJE'\r\n  GROUP BY category\r\n  ORDER BY sum(value/-100.0) desc"
    }
   ]
  },
  {
   "title": "Top 10 kategorii pod względem liczby transakcji",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT   \r\n  category as \"Kategoria\",\r\n  count(*)\r\nFROM bank_records\r\nWHERE \r\n  value < 0\r\n  AND date_trunc('MONTH', date) >= date_trunc('MONTH', $__timeFrom()::date)\r\n  AND date_trunc('MONTH', date) <= date_trunc('MONTH', $__timeTo()::date)\r\nGROUP BY category"
    }
   ]
  },
  {
   "title": "Wydatki na kategorie",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT   \r\n  category as \"Kategoria\",\r\n  sum(value/100.0)\r\nFROM bank_records\r\nWHERE \r\n  value < 0\r\n  AND date_trunc('MONTH', date) >= date_trunc('MONTH', $__timeFrom()::date)\r\n  AND date_trunc('MONTH', date) <= date_trunc('MONTH', $__timeTo()::date)\r\n  AND category != 'INWESTYCJE'\r\n  GROUP BY category"
    }
   ]
  },
  {
   "title": "Liczba transakcji",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT   \r\n  count(*)\r\nFROM bank_records\r\nWHERE \r\n  value < 0\r\n  AND date_trunc('MONTH', date) >= date_trunc('MONTH', $__timeFrom()::date)\r\n  AND date_trunc('MONTH', date) <= date_trunc('MONTH', $__timeTo()::date)"
    }
   ]
  },
  {
   "title": "Mediana kwoty transakcji",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.5) WITHIN GROUP (\r\n  order by value/100.0\r\n  )\r\nFROM bank_records\r\nWHERE \r\n  value < 0\r\n  AND date_trunc('MONTH', date) >= date_trunc('MONTH', $__timeFrom()::date)\r\n  AND date_trunc('MONTH', date) <= date_trunc('MONTH', $__timeTo()::date)\r\n  AND category != 'INWESTYCJE'"
    }
   ]
  },
  {
   "title": "Średnia kwota transakcji",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  count(*) AS \"Liczba transakcji\"\r\nFROM months m\r\nLEFT JOIN bank_records br ON m.month = date_trunc('MONTH', br.date)::date AND br.category != 'INWESTYCJE'\r\nWHERE br.value < 0"
    }
   ]
  },
  {
   "title": "Liczba wpływów",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT   \r\n  count(*)\r\nFROM bank_records\r\nWHERE \r\n  value > 0\r\n  AND date_trunc('MONTH', date) >= date_trunc('MONTH', $__timeFrom()::date)\r\n  AND date_trunc('MONTH', date) <= date_trunc('MONTH', $__timeTo()::date)"
    }
   ]
  },
  { "title": "Przegląd miesięczny", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Zarobki",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "WITH months as (\r\n  SELECT  \r\n  generate_series(\r\n    date_trunc('MONTH', $__timeFrom()::date),\r\n    date_trunc('MONTH', $__timeTo()::date),\r\n    interval '1 MONTH'\r\n  )::date as month)\r\n\r\n\r\nSELECT \r\n  m.month AS \"Miesiąc\", \r\n  sum(value)/100 AS \"Zarobki\"\r\nFROM months m\r\nLEFT JOIN bank_records br ON m.month = date_trunc('MONTH', br.date)::date AND br.category = 'WYNAGRODZENIE'\r\nGROUP BY m.month"
    }
   ]
  },
  {
   "title": "Wydatki",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "WITH months as (\r\n  SELECT  \r\n  generate_series(\r\n    date_trunc('MONTH', $__timeFrom()::date),\r\n    date_trunc('MONTH', $__timeTo()::date),\r\n    interval '1 MONTH'\r\n  )::date as month)\r\n\r\n\r\nSELECT \r\n  m.month AS \"Miesiąc\", \r\n  sum(value)/-100 AS \"Wydatki\"\r\nFROM months m\r\nLEFT JOIN bank_records br ON m.month = date_trunc('MONTH', br.date)::date AND br.category NOT IN ('WYNAGRODZENIE', 'INWESTYCJE', 'ZWROTY', 'FINANSE')\r\nwhere value < 0\r\nGROUP BY m.month\r\nORDER BY m.month asc"
    }
   ]
  },
  {
   "title": "Procent odkładanej wypłaty",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH months as (\r\n  SELECT  \r\n  generate_series(\r\n    date_trunc('MONTH', $__timeFrom()::date),\r\n    date_trunc('MONTH', $__timeTo()::date),\r\n    interval '1 MONTH'\r\n  )::date as month),\r\n\r\n  finances as (\r\n  SELECT \r\n    m.month AS \"Miesiąc\", \r\n    sum(CASE WHEN value < 0 then value else 0 end)/-100 AS \"Wydatki\",\r\n    sum(CASE WHEN value > 0 then value else 0 end)/100 AS \"Zarobki\"\r\n  FROM months m\r\n  LEFT JOIN bank_records br ON m.month = date_trunc('MONTH', br.date)::date AND br.category NOT IN ('INWESTYCJE', 'ZWROTY', 'FINANSE')\r\n  GROUP BY m.month\r\n  ORDER BY m.month asc\r\n  )\r\n\r\nSELECT \"Miesiąc\", 100 - \"Wydatki\"*100.0/\"Zarobki\" as \"Oszczędności\" from finances"
    }
   ]
  },
  {
   "title": "Wydatki",
   "type": "status-history",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "rawSql": "WITH months as (\r\n  SELECT  \r\n  generate_series(\r\n    date_trunc('MONTH', $__timeFrom()::date),\r\n    date_trunc('MONTH', $__timeTo()::date),\r\n    interval '1 MONTH'\r\n  )::date as month)\r\n\r\n\r\nSELECT \r\n  m.month AS \"Miesiąc\", \r\n  br.category AS \"Kategoria\",\r\n  sum(value)/-100 AS \"Wartość\"\r\nFROM months m\r\nLEFT JOIN bank_records br ON m.month = date_trunc('MONTH', br.date)::date AND br.category NOT IN ('WYNAGRODZENIE', 'INWESTYCJE', 'ZWROTY', 'FINANSE')\r\nwhere value < 0\r\nGROUP BY m.month, br.category\r\nORDER BY m.month asc"
    }
   ]
  },
  { "title": "Przegląd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Lista operacji",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  date as \"Data\",\r\n  operation_type as \"Typ operacji\",\r\n  value/100.0 as \"Wartość\",\r\n  title as \"Tytuł\",\r\n  category as \"Kategoria\",\r\n  description as \"Opis\"\r\nFROM bank_records \r\nWHERE \r\n  date_trunc('MONTH', date) >= date_trunc('MONTH', $__timeFrom()::date)\r\n  AND date_trunc('MONTH', date) <= date_trunc('MONTH', $__timeTo()::date)\r\nORDER BY date desc"
    }
   ]
  }
 ]
}